config_version: 0
Task: EyePupilEllipse
scorer: Zhiheng
date: Sep20
multianimalproject: false
identity: null
project_path: /Users/lizhiheng/Desktop/生物/dlc_projects/EyePupilEllipse-Zhiheng-2026-09-20
pose_config_path: null
engine: pytorch
video_sets:
  /Users/lizhiheng/Desktop/生物/dlc_projects/EyePupilEllipse-Zhiheng-2026-09-20/videos/first5minvedio.mp4:
    crop: 0, 928, 0, 736
  /Users/lizhiheng/Desktop/生物/dlc_projects/EyePupilEllipse-Zhiheng-2026-09-20/videos/20251031_Pluto_spont_1.mp4:
    crop: 0, 928, 0, 736
  /Users/lizhiheng/Desktop/生物/dlc_projects/EyePupilEllipse-Zhiheng-2026-09-20/videos/pluton2.mp4:
    crop: 0, 928, 0, 736
  /Users/lizhiheng/Desktop/生物/dlc_projects/EyePupilEllipse-Zhiheng-2026-09-20/videos/0_first5minvedio.mp4:
    crop: 0, 928, 0, 736
  /Users/lizhiheng/Desktop/生物/dlc_projects/EyePupilEllipse-Zhiheng-2026-09-20/videos/1_20251031_Pluto_spont_1.mp4:
    crop: 0, 928, 0, 736
  /Users/lizhiheng/Desktop/生物/dlc_projects/EyePupilEllipse-Zhiheng-2026-09-20/videos/2_pluton2.mp4:
    crop: 0, 928, 0, 736
bodyparts:
- pupil_top
- pupil_bottom
- pupil_left
- pupil_right
- eyelid_top
- eyelid_bottom
- eye_nasal_corner
- eye_temporal_corner
individuals:
- individual_1
uniquebodyparts: []
multianimalbodyparts: []
start: 0.0
stop: 0.8
numframes2pick: 20
skeleton:
- - pupil_top
  - pupil_bottom
- - pupil_left
  - pupil_right
- - eyelid_top
  - eyelid_bottom
- - eye_nasal_corner
  - eye_temporal_corner
skeleton_color: black
pcutoff: 0.6
dotsize: 17
alphavalue: 0.7
colormap: rainbow
TrainingFraction:
- 0.5
- 0.67
- 0.75
- 0.8
- 0.83
- 0.86
- 0.88
- 0.89
- 0.9
- 0.91
- 0.92
- 0.93
iteration: 0
default_net_type: resnet_50
default_augmenter: default
default_track_method: null
snapshotindex: -1
detector_snapshotindex: -1
batch_size: 8
detector_batch_size: 1
cropping: false
x1: 0
x2: 640
y1: 277
y2: 624
corner2move2:
- 50
- 50
move2corner: true
SuperAnimalConversionTables: null
resnet: null
croppedtraining: null
